import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/shared/Navbar";
import { ShoppingProvider } from "./context/ShoppingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AnelShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShoppingProvider>
          <Navbar />
          {children}
        </ShoppingProvider>
      </body>
    </html>
  );
}
